# Generated by Django 5.2.4 on 2025-08-01 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0002_alter_book_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': (('canaddbook', 'Can add book'), ('canchangebook', 'Can change book'), ('candeletebook', 'Can delete book'))},
        ),
        migrations.RemoveField(
            model_name='book',
            name='published_date',
        ),
    ]
