# Generated by Django 5.2.4 on 2025-08-02 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0007_alter_book_options_alter_book_author_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': (('canaddbook', 'Can add book'), ('canchangebook', 'Can change book'), ('candeletebook', 'Can delete book'))},
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
