# Generated by Django 5.2.4 on 2025-08-02 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0008_alter_book_options_alter_book_author_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('canaddbook', 'Can add book'), ('canchangebook', 'Can change book'), ('candeletebook', 'Can delete book')]},
        ),
    ]
